#!/usr/bin/env bash
# Install nginx
REDIRECT="\n\tlocation = /redirect_me {\n\t\treturn 301 https://www.google.com; \n\t}"
AFTER="server_name _;"

#commands
apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i "/$AFTER/a\ $REDIRECT" "/etc/nginx/sites-available/default"
service nginx restart
