#!/usr/bin/env bash
# Configure custom error page

#variables
ERROR="\n\terror_page 404 /error.html;\n\tlocation = /error.html { \n\t\t root /usr/share/nginx/html;\n\t\t internal;\n\t}\n"
AFTER_TEXT="server_name _;"
FILE="/etc/nginx/sites-available/default"
ERROR_FILE="/usr/share/nginx/html/error.html"
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.google.com; \n\t}"


#commands
apt-get -y update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > "$ERROR_FILE";

sed -i "/$AFTER_TEXT/a\ $REDIRECT" "/etc/nginx/sites-available/default"
sed -i "/$AFTER_TEXT/a\ $ERROR" "$FILE"

service nginx restart
