#!/usr/bin/env bash
# Configure a load balancer
FILE="/etc/haproxy/haproxy.cfg"
apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy

cat <<EOF >> $FILE
frontend myfrontend
    bind 0.0.0.0:80
    default_backend myservers
backend myservers
    server web-01 54.172.251.66:80
    server web-02 54.197.206.65:80
EOF
service haproxy restart
